QT -= core gui
CONFIG += c++11 console
CONFIG -= app_bundle

DEFINES += EGL_NO_X11=1

!isEmpty(QMAKE_LIBDIR_EGL): LIBS += -L$$QMAKE_LIBDIR_EGL
LIBS += $$QMAKE_LIBS_EGL
INCLUDEPATH += $$QMAKE_INCDIR_EGL

SOURCES += main.cpp
